# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Munoy'
  url:            munoy.github.io

paginate:         5

domain:           munoy.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url:              https://munoy.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl:          munoy.github.io       # place folder name if the site is served in a subfolder

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Munoy
